const SHIP_DEADLINE_HOURS = 72;
const AUTO_COMPLETE_DAYS = 10;

module.exports = {
  SHIP_DEADLINE_HOURS,
  AUTO_COMPLETE_DAYS,
  SHIP_DEADLINE_LABEL: `${SHIP_DEADLINE_HOURS} 小时`,
  AUTO_COMPLETE_LABEL: `${AUTO_COMPLETE_DAYS} 天`,
};
